#constantes a utilizar por el programa netstats.
LISTAR_OPERACIONES = "listar_operaciones"
CAMINO = "camino"
MAS_IMPORTANTES = "mas_importantes"
CONECTADOS = "conectados"
CICLO = "ciclo"
LECTURA = "lectura"
DIAMETRO = "diametro"
RANGO = "rango"
COMUNIDAD = "comunidad"
NAVEGACION = "navegacion"
CLUSTERING = "clustering"
FLECHA = " -> "
SIN_CAMINO = "No se encontro recorrido"
COSTO_CAMINO = "Costo: %d"
COMA = ", "
SIN_LECTURA = "No existe forma de leer las paginas en orden"
COEFICIENTE_CLUSTERING = "%.3f"